Repository newrelic/developer-toolkit, pull requests merged in 2019-12, with the labels that each got.

#4 Milestone + Initial presentation
  docs/_layouts/slide.html
  docs/_presentations/terraform-provider-overview.html
  docs/roadmap.markdown
Labels: documentation

#5 Update tf presentation
  docs/_presentations/terraform-provider-overview.html
Labels: documentation, enhancement

#6 Updates to TF Overview
  docs/_presentations/terraform-provider-overview.html
Labels: documentation, enhancement

#7 Enable analytics
  THIRD_PARTY_NOTICES.md
  docs/_includes/head.html
  docs/_includes/newrelic.html
Labels: enhancement

#8 Add RFC Links
  docs/_config.yml
  docs/index.markdown
  docs/roadmap.markdown
Labels: documentation

#10 Update README
  README.md
Labels: documentation

#11 updated readme to include RFC
  README.md
Labels: documentation
